version: "3.7"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:10.16-alpine
    container_name: node-app
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_LOCAL_NAME=$DB_LOCAL_NAME
      - DB_PROD_NAME=$DB_PROD_NAME
      - DB_HOST=db
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - LOCAL_CERT=$LOCAL_CERT
      - LOCAL_CERT_KEY=$LOCAL_CERT_KEY
      - LOCAL_CERT_PASS=$LOCAL_CERT_PASS
    ports:
      - "5555:5555"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:5.6
    container_name: db
    restart: unless-stopped
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_LOCAL_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASS
    volumes:
      - ~/DBs/MySQL:/var/lib/mysql
      - ~/DBs/MySQL/data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
